security:
    encoders:
        FreeBet\Bundle\UserBundle\Document\User: sha512

    role_hierarchy:
        ROLE_ADMIN:   [ROLE_USER, ROLE_MANAGER]
        ROLE_MANAGER: [ROLE_USER]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            form_login:
                csrf_provider: form.csrf_provider
                login_path:    fos_user_security_login
                check_path:    fos_user_security_check

    access_control:
        - { path: ^/(en\/|fr\/)?login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/group, roles: ROLE_MANAGER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
